exp_name: 'relaxing_independent_pixel_assumption'

# Parameters related to data
project_root: '/data/Rudra/vae_output_blur/vae_plus_plus'
data_root: '/data/Rudra/vae_output_blur/vae_plus_plus/data/data'
dataset: 'mnist'  # mnist (28x28x1) | fashion-mnist (28x28x1) | cifar10 (32x32x3) | celeb (64x64x3) | piece-wise (2)
num_workers: 4

# Parameters related to datasets
piece-wise:
  num_samples: 1000 # Number of samples to be taken from each of the linear section.
  num_sections: 3 # Number of linear sections 
  sample: 'uniform' # Way of sampling from each of the linear section. uniform | vertex-heavy

# Parameters related to training
use_cuda: True
batch_size: 64
init_type: 'normal'  # Initialization type for the network. normal | xavier | kaiming | orthogonal
gain: 0.02
kl_warmup: True
kl_beta: 1.0
loss_type: bce
lr: 0.0001
max_epochs: 1000
loggin_interval: 10

# Parameters related to current training
# TODO: Make this standard
img_h: 28
img_w: 28

# Parameters for encoders
mnist-encoder:
  ic: 1
  nef: 64
  hidden: 512
  zdim: 10

piece-wise-encoder:
  ic: 2
  hidden: 128
  zdim: 2

# Parameters for decoders
mnist-decoder:
  oc: 1
  ndf: 64
  zdim: 10
  hidden: 512
  mid_c: 512
  mid_h: 2
  mid_w: 2

piece-wise-decoder:
  oc: 2
  hidden: 128
  zdim: 2


