exp_name: 'relaxing_independent_pixel_assumption'

# Parameters related to data
data_root: '/Users/i23271/Downloads/PhD/relaxing_independent_pixel_assumption/data/data'
dataset: 'mnist'  # mnist (28x28x1) | fashion-mnist (28x28x1) | cifar10 (32x32x3) | celeb (64x64x3) | piece-wise (2)
num_workers: 4

# Parameters related to training
use_cuda: False
batch_size: 64

# Parameters for encoder
encoder:
  ic: 1
  nef: 64
  hidden: 256
  zdim: 10

# Parameters for decoder
decoder:
  oc: 1
  ndf: 8


